### ISSUE TITLE
Tab Formatting

### ISSUE THREAD

**Issue by silasgibbins** [bjw49/citation-network-explorer#22]
The tabs in the top right corner (network view and table view) don't look like tabs bc they are wrapped by the wider rectangle. Truncate the rectangle so it is a shape similar to the one attached.

<img width="185" alt="gecko_tabs" src="https://user-images.githubusercontent.com/35504615/35013309-0455a302-fadb-11e7-8af0-e4afeef0a823.PNG">

[BoundingRect.pdf](https://github.com/bjw49/citation-network-explorer/files/1636919/BoundingRect.pdf)

**Comment by bjw49** [comment]
Tabbing changed
